apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodocker
  template:
    metadata:
      labels:
        app: hellodocker
    spec:
      containers:
      - name: hellodocker
        image: sultan2004/hellodocker:1.0
        ports:
        - containerPort: 80